globalvar CHARMAP;
CHARMAP = ds_map_create()

//NUMBERS
ds_map_add(CHARMAP,"0",sp_n0)
ds_map_add(CHARMAP,"1",sp_n1)
ds_map_add(CHARMAP,"2",sp_n2)
ds_map_add(CHARMAP,"3",sp_n3)
ds_map_add(CHARMAP,"4",sp_n4)
ds_map_add(CHARMAP,"5",sp_n5)
ds_map_add(CHARMAP,"6",sp_n6)
ds_map_add(CHARMAP,"7",sp_n7)
ds_map_add(CHARMAP,"8",sp_n8)
ds_map_add(CHARMAP,"9",sp_n9)

//SYMBOLS
ds_map_add(CHARMAP,"!",sp_sExclamattion)
ds_map_add(CHARMAP,".",sp_sdot)
ds_map_add(CHARMAP,",",sp_scomma)
ds_map_add(CHARMAP," ",sp_sSpace)

//LETTERS
ds_map_add(CHARMAP,"a",sp_A)
ds_map_add(CHARMAP,"b",sp_B)
ds_map_add(CHARMAP,"c",sp_C)
ds_map_add(CHARMAP,"d",sp_D)
ds_map_add(CHARMAP,"e",sp_E)
ds_map_add(CHARMAP,"f",sp_F)
ds_map_add(CHARMAP,"g",sp_G)
ds_map_add(CHARMAP,"h",sp_H)
ds_map_add(CHARMAP,"i",sp_I)
ds_map_add(CHARMAP,"j",sp_J)
ds_map_add(CHARMAP,"k",sp_K)
ds_map_add(CHARMAP,"l",sp_L)
ds_map_add(CHARMAP,"m",sp_M)
ds_map_add(CHARMAP,"n",sp_N)
ds_map_add(CHARMAP,"o",sp_O)
ds_map_add(CHARMAP,"p",sp_P)
ds_map_add(CHARMAP,"q",sp_Q)
ds_map_add(CHARMAP,"r",sp_R)
ds_map_add(CHARMAP,"s",sp_S)
ds_map_add(CHARMAP,"t",sp_T)
ds_map_add(CHARMAP,"u",sp_U)
ds_map_add(CHARMAP,"v",sp_V)
ds_map_add(CHARMAP,"w",sp_W)
ds_map_add(CHARMAP,"x",sp_X)
ds_map_add(CHARMAP,"y",sp_Y)
ds_map_add(CHARMAP,"z",sp_Z)
